function getInfo() {
	window.numberOfQuestions = 	30;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"THE GEOMETRY GAME";
	window.questions = [		"WHAT IS THE DEFENITION OF A POINT?",
								"WHICH OF THE FOLLOWING FITS THE DEFINITION: PART OF A LINE. IT HAS 2 ENDPOINTS AND INCLUDES ALL OF THE POINTS IN-BETWEEN",
                                "A PLANE IS NAMED BY...?",
                                "WHERE DO TWO LINES INTERSECT?",
                                "IF LINE J IS PARALLEL TO LINE K, AND LINE L IS PERPENDICULAR TO LINE J, WHAT IS THE RELATIONSHIP BETWEEN LINES L&K??",
                                "WHERE DO TWO PLANES INTERSECT?",
                                "WHAT IS THE DISTANCE BETWEEN (-5,-6) AND (-3,-8)?",
                                "WHICH OF THE FOLLOWING WOULD NOT WORK AS A VALUE FOR DISTANCE?",
                                "WHAT IS THE DISTANCE BETWEEN (4,7) AND (2,2)?",
                                "WHAT IS THE DISTANCE BETWEEN (6,3,) AND (2,4)?",
                                "WHAT IS THE DISTANCE BETWEEN (9,5) AND (10,2)?",
                                "WHAT IS THE DEFINITION OF DISTANCE?",
                                "WHAT IS THE DEFINITION OF SLOPE?",
                                "FIND THE SLOPE OF POINTS (2,5) AND (-4,5)",
                                "FIND THE SLOPE OF POINTS (-9,4) AND (-9,2)",
                                "FIND THE SLOPE OF POINTS (-1,0) AND (3,8)",
                                "FIND THE SLOPE OF POINTS (2,0) and (2,4)",
                                "WHAT IS THE FORMULA FOR SLOPE?",
                                "WHAT IS THE DEFINITION OF AN ISOSCELES TRIANGLE?",
                                "WHAT IS THE DEFINITION OF AN EQUILATERAL TRIANGLE?",
                                "WHAT IS THE DEFINITION OF A SCALENE TRIANGLE?",
                                "WHAT IS THE MEASURE OF A RIGHT TRIANGLE?",
                                "WHAT IS THE MEASURE OF AN ACUTE TRIANGLE?",
                                "WHAT IS THE MEASURE OF AN OBTUSE ANGLE",
                                "WHAT IS THE DEFINITION OF A POLYGON?",
                                "WHICH POLYGON HAS 4 OR MORE CONGRUENT SIDES AND 4 RIGHT ANGLES?",
                                "WHAT IS THE DEFINITION OF A TWO-DIMENTIONAL FIGURE?",
                                "WHICH POLYGON HAS 3 SIDES?",
                                "WHICH POLYGON HAS 6 SIDES?",
                                "WHICH POLYGON HAS 5 SIDES?"];
	window.correctAnswer = [ 	"A", "C", "A", "B", "E", "D", "C", "A", "B","D", "B", "E", "C", "A", "B", "A", "D", "A", "A", "B", "E", "B", "B", "C", "D", "E", "B", "E", "B", "A"  ]; 
	window.answerA = [ 			"A POINT IS A LOCATION", 
								"A RAY", 
								"ANY 3 POINTS ON A PLANE NOT ON THE SAME LINE", 
								"AT A RAY", 
								"LINE L IS PARALLEL TO LINE K",
								"IN THE SKY",
								"74",
								"-4",
								"62",
								"8.9",
								"4.2",
								"HOW FAR I WILL RUN",
								"THE CHANGE IN X OVER THE CHANGE IN Y",
								"0",
								"0",
								"2",
								"7",
								"(Y2-Y1)/(X2-X1)",
								"A TRIANGLE WITH 2 CONGRUENT SIDES",
								"A TRIANGLE WITH 2 CONGRUENT SIDES",
								"A TRIANGLE WITH 2 CONGRUENT SIDES",
								"80 DEGREES",
								"BETWEEN 90 AND 180 DEGREES",
								"BETWEEN 50 AND 60 DEGREES",
								"ANY CLOSED FIGURE FORMED WITH 1 OR MORE STRAIGHT LINES",
								"A TRIANGLE",
								"A SHAPE",
								"A SQUARE",
								"A SQUARE",
								"A PENTAGON"];
	window.answerB = [ 			"A POINT IS THE EDGE OF A SLICE OF BREAD", 
								"A POINT", 
								"ANY 1 POINT ON THE PLANE", 
								"AT A POINT",
								"LINES J AND K ARE PERPENDICULAR",
								"AT ANOTHER PLANE",
								"63",
								"5" ,
								"THE SQUARE ROOT OF 29",
								"5.3",
								"3.1623",
								"A TYPE OF BREAD" ,
								"THE HILL'S THAT PEOPLE SKI ON",
								"2",
								"UNDEFINED",
								"4",
								"5",
								"X+Y",
								"A TRIANGLE WITH 3 CONGRUENT SIDES",
								"A TRIANGLE WITH 3 CONGRUENT SIDES",
								"A TRIANGLE WITH 3 CONGRUENT SIDES",
								"90 DEGREES",
								"BETWEEN 0 AND 90 DEGREES",
								"BETWEEN 0 AND 45 DEGREES",
								"ANY CLOSED FIGURE FORMED WITH 4 OR MORE STRAIGHT LINES",
								"A TRAPEZOID",
								"A FLAT FIGURE THAT CAN BE MEASURED IN 2 WAYS",
								"A HEXAGON",
								"A HEXAGON",
								"A HEXAGON"];
	window.answerC = [ 			"A POINT IS THE END OF A SHARP OBJECT",
								"A LINE SEGMENT",
								"ANY 4 POINTS ON THE SAME LINE", 
								"ON AN ANGLE", 
								"LINES L AND K ARE PARALLEL",
								"AT A VERTEX",
								"THE SQUARE ROOT OF 8",
								"20" ,
								"7.623",
								"2.354",
								"6.7243",
								"THE NAME OF A COORDINATE PLANE",
								"THE CHANGE IN Y OVER THE CHANGE IN X, OR RISE OVER RUN",
								"4",
								"6",
								"6",
								"2",
								"Y=MX+B",
								"A TRIANGLE WITH 4 CONGRUENT SIDES",
								"A TRIANGLE WITH 4 CONGRUENT SIDES",
								"A TRIANGLE WITH 4 CONGRUENT SIDES",
								"100 DEGREES",
								"BETWEEN 20 AND 50 DEGREES",
								"BETWEEN 90 AND 180 DEGREES",
								"ANY CLOSED FIGURE FORMED WITH 5 OR MORE STRAIGHT LINES",
								"A HEXAGON",
								"A DRAWING",
								"A TRAPEZOID",
								"A TRAPEZOID",
								"A SQUARE"];
	window.answerD = [ 			"A POINT IS A MEASUREMENT OF TIME",  
								"AN ANGLE",
								"ALL POINTS ON THE PLANE THAT AREN'T PART OF A LINE", 
								"AT MMSA",
								"LINES L AND J ARE ABOVE LINE K",
								"AT A LINE",
								"24" ,
								"8",
								"9.2",
								"4.1231",
								"6.42",
								"WHAT TIME IT IS RIGHT NOW",
								"RUN OVER RISE",
								"6",
								"10",
								"8",
								"UNDEFINED",
								"(Y2-Y1)+3",
								"A TRIANGLE WITH 5 CONGRUENT SIDES",
								"A TRIANGLE WITH 5 CONGRUENT SIDES",
								"A TRIANGLE WITH 5 CONGRUENT SIDES",
								"50 DEGREES",
								"BETWEEN 10 AND 20 DEGREES",
								"BETWEEN 10 AND 30 DEGREES",
								"ANY CLOSED FIGURE FORMED WITH 3 OR MORE STRAIGHT LINES",
								"A PENTAGON",
								"A 3-DIMENSIONAL FIGURE",
								"A RECTANGLE",
								"A RECTANGLE",
								"A RECTANGLE"];
	window.answerE = [ 			"ALL OF THE ABOVE",
								"PERPENDICULAR LINE", 
								"ANY 3 POINTS ON A LINE WITHIN THE PLANE", 
								"AT A LINE SEGMENT", 
								"LINES L AND K ARE PERPENDICULAR",
								"ON A RAY",
								"The SQUARE ROOT OF 7",
								"34",
								"5",
								"0.8736",
								"84",
								"HOW FAR TWO POINTS ARE FROM EACHOTHER ON A COORDINATE PLANE",
								"Y=MX+B",
								"8",
								"9",
								"10",
								"0",
								"X-Y",
								"A TRIANGLE WITH NO CONGRUENT SIDES",
								"A TRIANGLE WITH NO CONGRUENT SIDES",
								"A TRIANGLE WITH NO CONGRUENT SIDES",
								"40 DEGREES",
								"BETWEEN 70 AND 150 DEGREES",
								"BETWEEN 110 AND 120 DEGREES",
								"ANY CLOSED FIGURE FORMED WITH 7 OR MORE STRAIGHT LINES",
								"A SQUARE",
								"ALL OF THE ABOVE",
								"A TRIANGLE",
								"A TRIANGLE",
								"A TRIANGLE"];
	window.response = [ 		"A POINT IS A LOCATION. THE CORRECT ANSWER WAS A.", 
								"THE DEFINITION MATCHES WITH A LINE SEGMENT. THE CORRECT ANSWER WAS C.", 
								"A PLANE IS NAMED AFTER ANY 3 NON-COLINEAR POINTS ON THE PLANE OR AN UPPERCASE SCRIPT LETTER. CORRECT ANSWER WAS A.", 
								"TWO LINES INTERSECT AT A POINT. THE CORRECT ANSWER WAS B.", 
								"LINE L IS PERPENDICULAR TO LINE K. THE CORRECT ANSWER WAS E.",
								"THE SQUARE ROOT OF 7. THE CORRECT ANSWER WAS C." ,
								"DISTANCE CAN'T BE A NEGATIVE NUMBER. THE CORRECT ANSWER WAS A.",
								"THE SQUARE ROOT OF 29. THE CORRECT ANSWER WAS B.",
								"4.1231. THE CORRECT ANSWER WAS D.",
								"3.1623. THE CORRECT ANSWER WAS B.",
								"HOW FAR TWO POINTS ARE FROM EACHOTHER ON A COORDINATE PLANE. THE CORRECT ANSWER WAS E.",
								"THE CHANGE IN Y OVER THE CHANGE IN X, OR RISE OVER RUN. THE CORRECT ANSWER WAS C.",
								"0. THE CORRECT ANSWER WAS A.",
								"UNDEFINED. THE CORRECT ANSWER WAS B",
								"2. THE CORRECT ANSWER WAS A",
								"UNDEFINED. THE CORRECT ANSWER WAS D",
								"(Y2-Y1)/(X2-X1). THE CORRECT ANSWER WAS A",
								"A TRIANGLE WITH 2 CONGRUENT SIDES. THE CORRECT ANSWER WAS A.",
								"A TRIANGLE WITH 3 CONGRUENT SIDES. THE CORRECT ANSWER WAS B",
								"A TRIANGLE WITH NO CONGRUENT SIDES. THE CORRECT ANSWER WAS E",
								"90 DEGREES. THE CORRECT ANSWER WAS B",
								"BETWEEN 0 AND 90 DEGREES. THE CORRECT ANSWER WAS B",
								"BETWEEN 90 AND 180 DEGREES. THE CORRECT ANSWER WAS C",
								"ANY CLOSED FIGURE FORMED WITH 3 OR MORE STRAIGHT LINES. THE CORRECT ANSWER WAS D",
								"A SQUARE. THE CORRECT ANSWER WAS E.",
								"A FLAT FIGURE THAT CAN BE MEASURED IN 2 WAYS. THE CORRECT ANSWER WAS B",
								"A TRIANGLE. THE CORRECT ANSWER WAS E",
								"A HEXAGON. THE CORRECT ANSWER WAS B",
								"A PENTAGON. THE CORRECT ANSWER WAS A"];
							
}
						